name: Build
on:
  workflow_call:

jobs:
  test_action:
    runs-on: ubuntu-22.04
    name: Test OpenAPI spec validation
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set Node.js 20.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install --frozen-lockfile --link-duplicates
      - name: Build distribution
        run: yarn clean && yarn dist
      - name: Validate valid openapi file
        uses: ./
        with:
          openapi-file: 'fixtures/valid_openapi.yml'

  test_unit:
    runs-on: ubuntu-22.04
    name: Run unit tests
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set Node.js 20.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install --frozen-lockfile --link-duplicates
      - run: yarn test
