name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test_action:
    runs-on: ubuntu-22.04
    name: Test OpenAPI spec validation
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install --frozen-lockfile --link-duplicates
      - name: Build distribution
        run: yarn clean && yarn dist
      - name: Validate valid openapi file
        uses: ./
        with:
          openapi-file: 'fixtures/valid_openapi.yml'

  test_unit:
    runs-on: ubuntu-22.04
    name: Run unit tests
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install --frozen-lockfile --link-duplicates
      - run: yarn test

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [test_action, test_unit]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: true
          use_yarn: true
          token: "${{ secrets.GITHUB_TOKEN }}"
