name: Build and release the action

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-24.04
    name: "Build and release action"
    needs: [build]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          use_yarn: true
          token: "${{ secrets.GITHUB_TOKEN }}"
