on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test OpenAPI spec validation
    steps:
      - uses: actions/checkout@v3
      - name: Validate valid openapi file
        uses: ./
        with:
          openapi-file: 'fixtures/valid_openapi.yml'
  test_unit:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v3
      - name: yarn install
        run: yarn install
      - name: yarn test
        run: yarn test
